// <auto-generated />
namespace EfMigrationsSeedDebugDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addedrequiredannotationtoproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedrequiredannotationtoproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201508251205552_Added required annotation to product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
